version : '3'
services:
  mysql:
    image: "mysql"
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=""
    volumes:
      - virtualvolume
  app:
    image: "project1"
    ports:
      - "5000:5000"
    depends_on:
      - mysql
volumes:
  virtualvolume:
