version : '3.9'
services:
  mysql:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=mysql'
      - 'MYSQL_DATABASE=go_project'
    ports:
      - '3306:3306'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 30s
        timeout: 10s
        retries: 5
  app:
    image: "project1"
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - mysql 
volumes:
  virtualvolume:
